import type { Walkthrough, WalkthroughReference } from './types';
import { WalkthroughSection } from './WalkthroughSection';
import { WalkthroughTOC } from './WalkthroughTOC';
import { useMediaQuery } from '@/hooks/useMediaQuery';

interface WalkthroughViewerProps {
  walkthrough: Walkthrough;
  onBack: () => void;
}

export function WalkthroughViewer({ walkthrough, onBack }: WalkthroughViewerProps) {
  const isMobile = useMediaQuery('(max-width: 767px)');
  const demoCount = walkthrough.sections.filter((s) => s.demo).length;
  const refs = walkthrough.references;

  return (
    <div className="lp-shell" style={{ maxWidth: 1100, paddingBottom: 80 }}>
      {/* Back */}
      <button
        type="button"
        onClick={onBack}
        className="lp-nav-link"
        style={{ padding: '16px 0', display: 'inline-block' }}
      >
        ← Back to walkthroughs
      </button>

      {/* Paper header */}
      <header style={{ paddingBottom: 32 }}>
        <h2
          style={{
            fontFamily: 'var(--font-sans)',
            fontSize: 'clamp(22px, 4vw, 30px)',
            fontWeight: 700,
            color: 'var(--text-primary)',
            margin: '0 0 8px',
            lineHeight: 1.15,
            letterSpacing: '-0.03em',
          }}
        >
          {walkthrough.paper.title}
        </h2>
        <div
          style={{
            fontSize: 13,
            fontFamily: 'var(--font-mono)',
            color: 'var(--text-muted)',
            marginBottom: 6,
          }}
        >
          {walkthrough.paper.authors} ({walkthrough.paper.year})
        </div>
        {walkthrough.paper.eprintUrl && (
          <a
            href={walkthrough.paper.eprintUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="lp-nav-link"
            style={{ display: 'inline-block', marginBottom: 8, padding: 0 }}
          >
            eprint/{walkthrough.paper.eprintId} ↗
          </a>
        )}
        <div style={{ display: 'flex', gap: 8, marginTop: 8 }}>
          <span style={badgeStyle}>{walkthrough.sections.length} sections</span>
          <span style={badgeStyle}>{demoCount} interactive demos</span>
          {walkthrough.generatedBy === 'ai' && (
            <span style={{ ...badgeStyle, borderColor: 'var(--color-info-border)', color: 'var(--color-info)' }}>AI-generated</span>
          )}
        </div>
      </header>

      {/* Main layout: TOC + content */}
      <div style={{ display: 'flex', gap: 40 }}>
        {/* Sticky TOC on desktop */}
        {!isMobile && <WalkthroughTOC sections={walkthrough.sections} />}

        {/* Sections */}
        <div style={{ flex: 1, minWidth: 0 }}>
          {/* Mobile TOC (collapsible) */}
          {isMobile && (
            <details style={{ marginBottom: 24 }}>
              <summary
                style={{
                  fontSize: 13,
                  color: 'var(--text-secondary)',
                  cursor: 'pointer',
                  fontFamily: 'var(--font-mono)',
                }}
              >
                Table of contents
              </summary>
              <WalkthroughTOC sections={walkthrough.sections} />
            </details>
          )}

          {walkthrough.sections.map((section, i) => (
            <WalkthroughSection key={section.id} section={section} index={i} references={refs} />
          ))}

          {/* References */}
          {refs && refs.length > 0 && <ReferencesSection references={refs} />}

          {/* AI footer */}
          {walkthrough.generatedBy === 'ai' && (
            <div
              style={{
                padding: '16px 0',
                borderTop: '1px solid var(--border)',
                marginTop: 16,
                fontSize: 11,
                fontFamily: 'var(--font-mono)',
                color: 'var(--text-muted)',
                lineHeight: 1.5,
              }}
            >
              This walkthrough was generated by AI analysis of the paper.
              Demo mappings may not be perfectly aligned with every paper section.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function ReferencesSection({ references }: { references: WalkthroughReference[] }) {
  return (
    <section
      id="references"
      style={{
        padding: '32px 0',
        borderTop: '1px solid var(--border)',
      }}
    >
      <h3
        className="font-display"
        style={{
          fontSize: 18,
          fontWeight: 600,
          color: 'var(--text-primary)',
          margin: '0 0 16px',
        }}
      >
        References
      </h3>
      <ol
        style={{
          margin: 0,
          paddingLeft: 24,
          listStyleType: 'decimal',
        }}
      >
        {references.map((ref, i) => (
          <li
            key={ref.id}
            id={`ref-${ref.id}`}
            style={{
              fontSize: 13,
              color: 'var(--text-secondary)',
              lineHeight: 1.6,
              marginBottom: 10,
              fontFamily: 'var(--font-mono)',
            }}
          >
            <span style={{ color: 'var(--text-muted)', marginRight: 4 }}>[{i + 1}]</span>
            {ref.authors && (
              <span style={{ color: 'var(--text-primary)' }}>{ref.authors}. </span>
            )}
            <span style={{ fontStyle: 'italic' }}>"{ref.title}"</span>
            {ref.year && <span> ({ref.year})</span>}
            {ref.url && (
              <>
                {'. '}
                <a
                  href={ref.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{
                    color: 'var(--text-muted)',
                    textDecoration: 'underline',
                    textUnderlineOffset: 2,
                    wordBreak: 'break-all',
                  }}
                >
                  {ref.url}
                </a>
              </>
            )}
            {ref.note && (
              <span style={{ color: 'var(--text-muted)' }}> — {ref.note}</span>
            )}
          </li>
        ))}
      </ol>
    </section>
  );
}

const badgeStyle: React.CSSProperties = {
  fontSize: 10,
  fontWeight: 400,
  color: 'var(--text-muted)',
  padding: '3px 10px',
  borderRadius: 6,
  border: '1px solid var(--border)',
  fontFamily: 'var(--font-mono)',
  letterSpacing: '0.04em',
  textTransform: 'uppercase',
};
