import type { Walkthrough } from './types';
import { WalkthroughSection } from './WalkthroughSection';
import { WalkthroughTOC } from './WalkthroughTOC';
import { useMediaQuery } from '@/hooks/useMediaQuery';

interface WalkthroughViewerProps {
  walkthrough: Walkthrough;
  onBack: () => void;
}

export function WalkthroughViewer({ walkthrough, onBack }: WalkthroughViewerProps) {
  const isMobile = useMediaQuery('(max-width: 767px)');
  const demoCount = walkthrough.sections.filter((s) => s.demo).length;

  return (
    <div style={{ maxWidth: 1100, margin: '0 auto', padding: '0 24px 80px' }}>
      {/* Back */}
      <button
        onClick={onBack}
        style={{
          fontSize: 12,
          color: 'var(--text-muted)',
          background: 'none',
          border: 'none',
          cursor: 'pointer',
          fontFamily: 'var(--font-display)',
          padding: '16px 0',
        }}
      >
        ← Back to walkthroughs
      </button>

      {/* Paper header */}
      <header style={{ paddingBottom: 32 }}>
        <h2
          className="font-display"
          style={{
            fontSize: 26,
            fontWeight: 600,
            color: 'var(--text-primary)',
            margin: '0 0 8px',
            lineHeight: 1.2,
          }}
        >
          {walkthrough.paper.title}
        </h2>
        <div
          style={{
            fontSize: 13,
            color: 'var(--text-muted)',
            marginBottom: 6,
          }}
        >
          {walkthrough.paper.authors} ({walkthrough.paper.year})
        </div>
        {walkthrough.paper.eprintUrl && (
          <a
            href={walkthrough.paper.eprintUrl}
            target="_blank"
            rel="noopener noreferrer"
            style={{
              fontSize: 12,
              color: 'var(--text-muted)',
              textDecoration: 'underline',
              display: 'inline-block',
              marginBottom: 8,
            }}
          >
            eprint/{walkthrough.paper.eprintId}
          </a>
        )}
        <div style={{ display: 'flex', gap: 8, marginTop: 8 }}>
          <span style={badgeStyle}>{walkthrough.sections.length} sections</span>
          <span style={badgeStyle}>{demoCount} interactive demos</span>
          {walkthrough.generatedBy === 'ai' && (
            <span style={{ ...badgeStyle, borderColor: 'var(--status-error)' }}>AI-generated</span>
          )}
        </div>
      </header>

      {/* Main layout: TOC + content */}
      <div style={{ display: 'flex', gap: 40 }}>
        {/* Sticky TOC on desktop */}
        {!isMobile && <WalkthroughTOC sections={walkthrough.sections} />}

        {/* Sections */}
        <div style={{ flex: 1, minWidth: 0 }}>
          {/* Mobile TOC (collapsible) */}
          {isMobile && (
            <details style={{ marginBottom: 24 }}>
              <summary
                style={{
                  fontSize: 13,
                  color: 'var(--text-secondary)',
                  cursor: 'pointer',
                  fontFamily: 'var(--font-display)',
                }}
              >
                Table of contents
              </summary>
              <WalkthroughTOC sections={walkthrough.sections} />
            </details>
          )}

          {walkthrough.sections.map((section, i) => (
            <WalkthroughSection key={section.id} section={section} index={i} />
          ))}

          {/* Footer */}
          {walkthrough.generatedBy === 'ai' && (
            <div
              style={{
                padding: '16px 0',
                borderTop: '1px solid var(--border)',
                marginTop: 16,
                fontSize: 11,
                color: 'var(--text-muted)',
                lineHeight: 1.5,
              }}
            >
              This walkthrough was generated by AI analysis of the paper.
              Demo mappings may not be perfectly aligned with every paper section.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

const badgeStyle: React.CSSProperties = {
  fontSize: 11,
  color: 'var(--text-muted)',
  padding: '3px 8px',
  borderRadius: 6,
  border: '1px solid var(--border)',
  fontFamily: 'var(--font-mono)',
};
