import {
  CurveConfig,
  CurvePoint,
  addPoints,
  scalarMultiply,
  enumerateCurvePoints,
  mod,
  DEFAULT_CURVE,
} from './logic';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface PairingConfig {
  curve: CurveConfig;
  generator: CurvePoint; // base point G
  groupOrder: number; // order of the subgroup generated by G
}

export interface PairingResult {
  inputP: CurvePoint | null;
  inputQ: CurvePoint | null;
  outputValue: number; // element in the "target group" Z_n
  pScalar: number; // discrete log of P w.r.t. G (or -1)
  qScalar: number; // discrete log of Q w.r.t. G (or -1)
}

export interface BilinearityDemo {
  a: number;
  b: number;
  P: CurvePoint;
  Q: CurvePoint;
  aP: CurvePoint | null;
  bQ: CurvePoint | null;
  ePQ: number; // e(P, Q)
  eaPbQ: number; // e(aP, bQ)
  ePQab: number; // e(P,Q)^(ab) mod n
  bilinearityHolds: boolean;
}

export interface VerificationEquation {
  name: string;
  description: string;
  lhs: { pairings: { P: string; Q: string }[] };
  rhs: { pairings: { P: string; Q: string }[] };
  lhsValue: number;
  rhsValue: number;
  holds: boolean;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Modular exponentiation: base^exp mod m (non-negative exp). */
function modPow(base: number, exp: number, m: number): number {
  if (m === 1) return 0;
  let result = 1;
  base = mod(base, m);
  let e = exp;
  while (e > 0) {
    if (e & 1) result = mod(result * base, m);
    e >>= 1;
    base = mod(base * base, m);
  }
  return result;
}

/**
 * Find a primitive root (generator) of Z_n* where n is prime.
 * Falls back to the smallest primitive root.
 */
function findPrimitiveRoot(n: number): number {
  if (n <= 1) return 1;
  if (n === 2) return 1;

  // Factor n-1
  const phi = n - 1;
  const factors: number[] = [];
  let temp = phi;
  for (let d = 2; d * d <= temp; d++) {
    if (temp % d === 0) {
      factors.push(d);
      while (temp % d === 0) temp = Math.floor(temp / d);
    }
  }
  if (temp > 1) factors.push(temp);

  // Find smallest primitive root
  for (let g = 2; g < n; g++) {
    let isPrimitive = true;
    for (const f of factors) {
      if (modPow(g, Math.floor(phi / f), n) === 1) {
        isPrimitive = false;
        break;
      }
    }
    if (isPrimitive) return g;
  }

  return 2; // fallback — should not reach here for a valid prime
}

/**
 * Compare two curve points for equality (both null = equal).
 */
function pointsEqual(
  a: CurvePoint | null,
  b: CurvePoint | null,
): boolean {
  if (a === null && b === null) return true;
  if (a === null || b === null) return false;
  return a.x === b.x && a.y === b.y;
}

// ---------------------------------------------------------------------------
// Core functions
// ---------------------------------------------------------------------------

/**
 * Find the order of the subgroup generated by `generator` on the given curve.
 * Repeatedly adds the generator to itself until hitting the point at infinity.
 */
export function findSubgroupOrder(
  curve: CurveConfig,
  generator: CurvePoint,
): number {
  let current: CurvePoint | null = generator;
  let order = 1;
  // Upper bound: by Hasse's theorem, the group order is at most p + 1 + 2*sqrt(p)
  const maxOrder = curve.p + 1 + 2 * Math.ceil(Math.sqrt(curve.p));
  while (current !== null && order <= maxOrder) {
    current = addPoints(current, generator, curve);
    order++;
  }
  if (current !== null) {
    // Generator does not produce a finite subgroup — should not happen
    // for a valid point on a valid curve, but handle gracefully.
    return -1;
  }
  return order;
}

/**
 * Build a PairingConfig by finding a generator with a reasonably-sized subgroup
 * (order > 3). Uses the provided curve or DEFAULT_CURVE.
 */
export function buildPairingConfig(
  curve: CurveConfig = DEFAULT_CURVE,
): PairingConfig {
  const points = enumerateCurvePoints(curve);

  // Try each point as a potential generator, pick the one with the
  // largest subgroup order (which will be a good generator for the demo).
  let bestGenerator: CurvePoint = points[0]!;
  let bestOrder = 1;

  for (const pt of points) {
    const order = findSubgroupOrder(curve, pt);
    if (order > bestOrder) {
      bestOrder = order;
      bestGenerator = pt;
    }
    // If we found a generator of the full group + infinity, that's ideal
    if (bestOrder === points.length + 1) break;
  }

  return {
    curve,
    generator: bestGenerator,
    groupOrder: bestOrder,
  };
}

/**
 * Brute-force discrete log: find k in [0, groupOrder) such that kG = point.
 * Returns 0 for the point at infinity, -1 if point is not in the subgroup.
 */
export function discreteLog(
  config: PairingConfig,
  point: CurvePoint | null,
): number {
  if (point === null) return 0;

  let current: CurvePoint | null = null;
  for (let k = 0; k < config.groupOrder; k++) {
    if (pointsEqual(current, point)) return k;
    current = addPoints(current, config.generator, config.curve);
  }

  return -1; // not in subgroup
}

/**
 * Compute the toy pairing e(P, Q).
 *
 * Since we know discrete logs over the small group, we define:
 *   e(P, Q) = g_T^(dlog_P * dlog_Q) mod n
 * where g_T is a primitive root of Z_n*, n = groupOrder.
 *
 * This is bilinear: e(aP, bQ) = g_T^(a*dlog_P * b*dlog_Q)
 *                              = (g_T^(dlog_P * dlog_Q))^(ab)
 *                              = e(P, Q)^(ab)
 *
 * Identity: e(O, Q) = g_T^(0 * dlog_Q) = g_T^0 = 1
 */
export function toyPairing(
  config: PairingConfig,
  P: CurvePoint | null,
  Q: CurvePoint | null,
): PairingResult {
  const n = config.groupOrder;
  const pScalar = discreteLog(config, P);
  const qScalar = discreteLog(config, Q);

  // If either point is not in the subgroup, return a sentinel
  if (pScalar === -1 || qScalar === -1) {
    return {
      inputP: P,
      inputQ: Q,
      outputValue: 0,
      pScalar: pScalar,
      qScalar: qScalar,
    };
  }

  const gT = findPrimitiveRoot(n);
  const exponent = mod(pScalar * qScalar, n);
  const outputValue = modPow(gT, exponent, n);

  return {
    inputP: P,
    inputQ: Q,
    outputValue,
    pScalar,
    qScalar,
  };
}

/**
 * Demonstrate the bilinearity property: e(aP, bQ) = e(P, Q)^(ab).
 * If P or Q are not provided, uses the generator G.
 */
export function demonstrateBilinearity(
  config: PairingConfig,
  a: number,
  b: number,
  P?: CurvePoint,
  Q?: CurvePoint,
): BilinearityDemo {
  const effectiveP = P ?? config.generator;
  const effectiveQ = Q ?? config.generator;
  const n = config.groupOrder;

  const aP = scalarMultiply(effectiveP, a, config.curve).result;
  const bQ = scalarMultiply(effectiveQ, b, config.curve).result;

  const ePQ = toyPairing(config, effectiveP, effectiveQ).outputValue;
  const eaPbQ = toyPairing(config, aP, bQ).outputValue;

  const ab = mod(a * b, n);
  const ePQab = modPow(ePQ, ab, n);

  return {
    a,
    b,
    P: effectiveP,
    Q: effectiveQ,
    aP,
    bQ,
    ePQ,
    eaPbQ,
    ePQab,
    bilinearityHolds: eaPbQ === ePQab,
  };
}

/**
 * Simulate a simplified Groth16 verification equation.
 *
 * Real Groth16: e(A, B) = e(alpha, beta) * e(L, gamma) * e(C, delta)
 * where L encodes public inputs.
 *
 * In the toy model, every curve point is kG for some scalar k.
 * The toy pairing maps e(aG, bG) -> g_T^(ab mod n) where n = group order.
 * "Multiplication" of pairing outputs corresponds to addition of exponents.
 *
 * Verification in the exponent domain:
 *   a_s * b_s  ≡  alpha_s * beta_s + l_s * gamma_s + c_s * delta_s  (mod n)
 *
 * We choose setup scalars, pick a and b, then derive c_s to balance.
 */
export function simulateGroth16Verify(
  config: PairingConfig,
): VerificationEquation {
  const n = config.groupOrder;

  // Choose "trusted setup" scalars (all reduced mod n, nonzero where needed)
  const alpha_s = mod(2, n);
  const beta_s = mod(3, n);
  const gamma_s = mod(1, n); // gamma = 1 simplifies: l_s * 1 = l_s
  const delta_s = mod(1, n); // delta = 1 simplifies: c_s * 1 = c_s
  const l_s = mod(4, n); // public-input scalar

  // Proof elements: pick a_s, b_s, derive c_s
  const a_s = mod(6, n) || 1;
  const b_s = mod(8, n) || 1;

  // Equation: a_s*b_s = alpha_s*beta_s + l_s*gamma_s + c_s*delta_s  (mod n)
  // Since delta_s = 1: c_s = a_s*b_s - alpha_s*beta_s - l_s*gamma_s  (mod n)
  const c_s = mod(
    a_s * b_s - alpha_s * beta_s - l_s * gamma_s,
    n,
  );

  // Compute exponents for the pairing equation
  const lhsExp = mod(a_s * b_s, n);
  const rhsExp = mod(
    alpha_s * beta_s + l_s * gamma_s + c_s * delta_s,
    n,
  );

  const gT = findPrimitiveRoot(n);
  const lhsValue = modPow(gT, lhsExp, n);
  const rhsValue = modPow(gT, rhsExp, n);

  return {
    name: 'Groth16',
    description:
      'e(A, B) = e(\u03b1G, \u03b2G) \u00b7 e(LG, \u03b3G) \u00b7 e(C, \u03b4G)',
    lhs: { pairings: [{ P: 'A', Q: 'B' }] },
    rhs: {
      pairings: [
        { P: '\u03b1G', Q: '\u03b2G' },
        { P: 'LG', Q: '\u03b3G' },
        { P: 'C', Q: '\u03b4G' },
      ],
    },
    lhsValue,
    rhsValue,
    holds: lhsValue === rhsValue,
  };
}

/**
 * Simulate KZG polynomial commitment verification.
 *
 * Real KZG: e(C - [v]G, H) = e(pi, [s]H - [z]H)
 * where C = commitment, v = claimed evaluation, z = evaluation point,
 * s = secret from setup, pi = opening proof.
 *
 * In the discrete-log domain with our toy pairing:
 *   (c - v) * h ≡ pi * (s - z) * h   (mod n)
 *   => c - v ≡ pi * (s - z)           (mod n)
 *   => pi ≡ (c - v) / (s - z)         (mod n)
 *
 * Parameters polyValue, evalPoint, commitment are optional scalars.
 */
export function simulateKZGVerify(
  config: PairingConfig,
  polyValue?: number,
  evalPoint?: number,
  commitment?: number,
): VerificationEquation {
  const n = config.groupOrder;

  // Defaults (all reduced mod n)
  const s = 9 % n || 1; // trusted setup secret
  const h = 3 % n || 1; // "second generator" scalar
  const z = mod(evalPoint ?? 4, n); // evaluation point
  const v = mod(polyValue ?? 7, n); // p(z) = v
  const c = mod(commitment ?? 11, n); // commitment scalar

  // Compute pi = (c - v) / (s - z) mod n
  const numerator = mod(c - v, n);
  const denominator = mod(s - z, n);

  // Find inverse of denominator mod n (brute force since n may not be prime)
  let denominatorInv = -1;
  for (let i = 0; i < n; i++) {
    if (mod(i * denominator, n) === 1) {
      denominatorInv = i;
      break;
    }
  }

  // If no inverse exists, adjust s to avoid the problem
  let adjustedS = s;
  if (denominatorInv === -1) {
    // Try different s values until we get an invertible (s - z)
    for (let tryS = 2; tryS < n; tryS++) {
      const d = mod(tryS - z, n);
      for (let i = 0; i < n; i++) {
        if (mod(i * d, n) === 1) {
          denominatorInv = i;
          adjustedS = tryS;
          break;
        }
      }
      if (denominatorInv !== -1) break;
    }
  }

  const pi = denominatorInv === -1 ? 0 : mod(numerator * denominatorInv, n);
  const effectiveDenom = mod(adjustedS - z, n);

  const lhsScalar = mod(c - v, n);

  const gT = findPrimitiveRoot(n);
  const lhsExp = mod(lhsScalar * h, n);
  const rhsExp = mod(pi * effectiveDenom * h, n);

  const lhsValue = modPow(gT, lhsExp, n);
  const rhsValue = modPow(gT, rhsExp, n);

  return {
    name: 'KZG',
    description:
      'e(C - [v]G, H) = e(\u03c0, [s]H - [z]H)',
    lhs: { pairings: [{ P: 'C - [v]G', Q: 'H' }] },
    rhs: { pairings: [{ P: '\u03c0', Q: '[s-z]H' }] },
    lhsValue,
    rhsValue,
    holds: lhsValue === rhsValue,
  };
}

/**
 * Compute the full pairing table: e(iG, jG) for i, j in [0, order).
 * Returns a 2D array indexed [i][j].
 */
export function pairingTable(config: PairingConfig): number[][] {
  const n = config.groupOrder;
  const gT = findPrimitiveRoot(n);

  const table: number[][] = [];
  for (let i = 0; i < n; i++) {
    const row: number[] = [];
    for (let j = 0; j < n; j++) {
      const exponent = mod(i * j, n);
      row.push(modPow(gT, exponent, n));
    }
    table.push(row);
  }

  return table;
}

// Re-export for convenience
export { modPow, findPrimitiveRoot, pointsEqual };
