import type { AttackScenario } from './types';

export const ECDLP_TOY_FIELD: AttackScenario = {
  id: 'ecdlp-toy-field',
  demoId: 'elliptic',
  title: 'Break ECDLP on a Toy Curve',
  difficulty: 'intermediate',
  briefing: {
    goal: 'Recover the secret scalar k given only the generator G and the public point Q = k·G.',
    adversarySees: [
      'The curve equation y² = x³ + ax + b (mod p)',
      'The generator point G',
      'The public point Q = k·G',
      'The group order n',
    ],
    adversaryControls: [
      'Unlimited computation over the toy field',
    ],
    adversaryCannotDo: [
      'Observe the secret scalar k directly',
      'Modify the curve parameters',
    ],
  },
  steps: [
    {
      id: 'setup-curve',
      instruction: 'A curve over GF(97) is loaded with a known generator G. The "victim" has a secret scalar k and publishes Q = k·G. Your goal: find k.',
      observation: 'The curve has ~100 points. The group generated by G has order n. All points are visible on the scatter plot.',
      adversaryNarration: 'I can see every point on the curve. With ~100 points, I can enumerate all scalar multiples of G to find which one matches Q.',
      demoAction: {
        type: 'LOAD_ECDLP_CHALLENGE',
        payload: {
          curve: { p: 97, a: 2, b: 3 },
          secretScalar: 17,
        },
      },
    },
    {
      id: 'enumerate-multiples',
      instruction: 'Use the scalar slider to walk through 1·G, 2·G, 3·G, ... and watch the result point. Stop when the result matches Q.',
      userAction: { description: 'Drag the scalar slider and observe when k·G matches the target point Q.' },
      observation: 'Each slider position shows a different point. The double-and-add trace in the panel shows how the scalar multiplication works step by step.',
      adversaryNarration: 'I am doing a brute-force search: trying every k from 1 to n. Over this tiny field, this takes milliseconds.',
    },
    {
      id: 'found-secret',
      instruction: 'You found the secret scalar! Over a toy field with ~100 points, brute-force enumeration is trivial.',
      observation: 'The scalar that produces Q has been found. This is the discrete logarithm: k = dlog_G(Q).',
      adversaryNarration: 'Success! I recovered k by trying all possibilities. Total work: at most n operations. Over GF(97) this is instant.',
      demoAction: {
        type: 'REVEAL_ECDLP_SOLUTION',
      },
    },
    {
      id: 'why-production-safe',
      instruction: 'Now consider a production curve like secp256k1 (Bitcoin) with a 256-bit group order. The same brute-force would require ~2²⁵⁶ operations.',
      observation: 'The best known attack (Pollard rho) takes √n ≈ 2¹²⁸ operations. At 10 billion operations/second, this would take longer than the age of the universe.',
      adversaryNarration: 'Over a real curve, my brute-force is hopeless. Even Pollard rho needs ~2¹²⁸ steps. The toy field teaches the math; the production field provides the security.',
    },
  ],
  conclusion: {
    succeeded: true,
    explanation: 'On the toy curve, ECDLP is trivially breakable by enumeration. The attack succeeds because the group order is small enough (~100) to search exhaustively. Production curves use 256-bit group orders where the same attack is computationally infeasible.',
    securityGuarantee: 'ECDLP security scales exponentially with the bit length of the group order. A 256-bit curve provides ~128 bits of security against the best known attacks (Pollard rho). This is why the same algebraic structure is secure at production scale but breakable at toy scale.',
    realWorldExample: 'ECDLP hardness secures Bitcoin (secp256k1), Ethereum (secp256k1), TLS/HTTPS (P-256), Signal Protocol (Curve25519), and all pairing-based SNARKs (BN254, BLS12-381).',
  },
};
